package icbm.classic.app.test.gui;

import icbm.classic.app.test.tools.blast.PanelLargeBlast;
import icbm.classic.app.test.tools.gas.PanelGasCloud;
import icbm.classic.app.test.tools.impact.PanelMissileAccuracy;
import icbm.classic.app.test.tools.path.PanelMissilePath;
import icbm.classic.app.test.tools.redmatter.PanelRedmatterBlast;

import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @see <a href="https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/license.md">License</a> for what you can and can't do with the code.
 * Created by Dark(DarkGuardsman, Robert) on 3/1/2018.
 */
public class MainFrame extends JFrame implements ActionListener
{
    public MainFrame()
    {
        //Set frame properties
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 800);
        setMinimumSize(new Dimension(800, 800));
        setLocation(200, 200);
        setTitle("Missile Calculator and Visualizer");

        add(buildCenter());

        pack();
    }

    protected JTabbedPane buildCenter()
    {
        JTabbedPane tabbedPane = new JTabbedPane();

        //Path test calculator
        tabbedPane.addTab("Path", null, new PanelMissilePath(),  "Calculator and visualizer for missile paths");

        //Impact calculator
        tabbedPane.addTab("Accuracy", null, new PanelMissileAccuracy(),  "Calculator and visualizer for missile impact accuracy");

        //Large thread visualizer
        tabbedPane.addTab("Blast Raytracing", null, new PanelLargeBlast(),  "Visualizer for large thread [rotation based ray trace] used ICBM's Nuclear/Sonic/Rot/Beam Explosive");

        //Redmatter scaling visualizer
        tabbedPane.addTab("Redmatter Scale", null, new PanelRedmatterBlast(),  "Visualizer for scale of redmatter renders and logic");

        //Entity Spawn
        //tabbedPane.addTab("Spawning", null, new PanelEntitySpawning(),  "Calculator and visualizer for MC1.12 entity random spawn point generator");

        //Sin vs cos TODO move to math tab
        //tabbedPane.addTab("Sin & cos", null, new PanelWave(),  "Calculator and visualizer for cos and sin function");

        //Sin wave generator TODO move to math tab
        //tabbedPane.addTab("Sin Wave Gen", null, new PanelSinGenerator(),  "Sin Wave generator, useful for testing args for sin wave creation");

        //Sin wave generator
        tabbedPane.addTab("Gas Cloud", null, new PanelGasCloud(),  "Visualizer for gas cloud generated by ICBM's Chemical Explosive");


        return tabbedPane;
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {

    }
}
